### ISSUE TITLE
Game Creation API

### ISSUE THREAD

**Issue by nicolodavis** [nicolodavis/boardgame.io#207]
- [x] `create` and `join` calls #189 
- [x] ability to protect API with a secret #204 
- [ ] ability to pass arbitrary data to the `create` call that is eventually passed as an argument to `Game.setup`.
- [ ] simple web lobby implementation #197 
- [ ] ability to assign a bot to a player.

**Comment by nicolodavis** [comment]
Marking this as a duplicate of #354
